service: telegram-bot-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": [ "ShipperingUsers", "Arn" ] }

functions:
  handle-message:
    handler: src/handler.handleMessage
    events:
      - http: GET /
      - http: POST /
    environment:
      TELEGRAM_TOKEN: ${ssm:${sls:stage}-telegram-token}
      WEATHER_KEY: ${ssm:weather-key}
      TRANSLATE_KEY: ${ssm:translate-key}
      STAGE: ${sls:stage}

package:
  individually: true
  include:
    - na-zare.ogg

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: webpack.config.ts
    includeModules: true

resources:
  Resources:
    ShipperingUsers:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${sls:stage}-shippering-users
        AttributeDefinitions:
          - AttributeName: chatId
            AttributeType: S
        KeySchema:
          - AttributeName: chatId
            KeyType: HASH
