service: telegram-bot-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  region: eu-west-1

functions:
  handle-message:
    handler: src/handler.handleMessage
    events:
      - http: GET /
      - http: POST /
    environment:
      TELEGRAM_TOKEN: ${ssm:${sls:stage}-telegram-token}
      WEATHER_KEY: ${ssm:weather-key}
      TRANSLATE_KEY: ${ssm:translate-key}

package:
  individually: true
  include:
    - na-zare.ogg

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: webpack.config.ts
    includeModules: true
